// pt-BR exercise names — EXDB indices 1104–1323
export default {
  "2206": "Abdominal reverso com rolo",
  "2203": "Flexão, depressão e retração escapulares sentadas com rolo",
  "2209": "Flexão, depressão e retração escapulares sentadas em uma perna com rolo",
  "2207": "Alongamento lateral de dorsais com rolo",
  "0680": "Subida na corda",
  "0685": "Corrida",
  "0684": "Corrida no aparelho",
  "1585": "Alongamento do corredor",
  "0687": "Abdominal russo",
  "3012": "Mergulho escapular",
  "3021": "Flexão escapular",
  "0688": "Barra fixa escapular",
  "3219": "Salto tesoura (masculino)",
  "1390": "Alongamento de panturrilha sentado (masculino)",
  "1424": "Alongamento de glúteos sentado",
  "0689": "Elevação de pernas sentada",
  "0690": "Alongamento lombar sentado",
  "2567": "Alongamento do piriforme sentado",
  "0691": "Abdominal lateral sentado na parede",
  "1587": "Sequência de flexão sentada com pernas afastadas",
  "0697": "Flexão nórdica autoassistida",
  "1766": "Flexão nórdica autoassistida",
  "0696": "Flexão nórdica autoassistida no chão",
  "3222": "Salto com meio agachamento (masculino)",
  "3656": "Corrida com passadas curtas",
  "1763": "Barra fixa com pegada na largura dos ombros",
  "3699": "Toque nos ombros",
  "0699": "Flexão de braços com toque nos ombros",
  "1774": "Ponte lateral com abdução do quadril",
  "0705": "Ponte lateral — variação 2",
  "0709": "Elevação lateral de pernas nas paralelas",
  "0710": "Abdução lateral do quadril",
  "1358": "Alongamento lateral deitado no chão",
  "3667": "Adução de quadril deitado de lado (masculino)",
  "1775": "Prancha lateral com adução do quadril",
  "0716": "Alongamento lateral do pescoço com pressão",
  "0717": "Flexão lateral de braços",
  "0721": "Alongamento lateral do punho com tração",
  "0720": "Barra fixa com o queixo de um lado para o outro",
  "3213": "Toque nos pés de um lado para o outro (masculino)",
  "0725": "Flexão de braços unilateral",
  "3645": "Ponte unilateral com perna estendida",
  "0727": "Elevação de panturrilha unilateral sobre halter",
  "0730": "Deslizamento unilateral na plataforma",
  "1759": "Agachamento unilateral tipo pistola (masculino)",
  "1489": "Agachamento sissy",
  "0735": "Abdominal completo — variação 2",
  "3679": "Abdominal completo com braços sobre o peito",
  "3361": "Saltos do patinador",
  "2142": "Esqui no SkiErg",
  "3671": "Salto lateral do esquiador",
  "3304": "Rotação invertida na barra",
  "1425": "Leg press 45° unilateral no trenó",
  "0738": "Elevação de panturrilhas no leg press 45°",
  "0739": "Leg press 45°",
  "1464": "Leg press 45° — vista traseira",
  "1463": "Leg press 45° — vista lateral",
  "0740": "Leg press 45° com base aberta",
  "1391": "Elevação de panturrilhas no leg press",
  "0741": "Agachamento hack com base fechada no trenó",
  "0742": "Elevação de panturrilhas inclinada para a frente no trenó",
  "0743": "Agachamento hack no trenó",
  "2334": "Elevação de panturrilhas deitada no trenó",
  "0744": "Agachamento deitado no trenó",
  "1392": "Elevação de panturrilha unilateral no leg press",
  "1496": "Golpe com marreta",
  "0746": "Encolhimento com barra por trás no Smith",
  "0747": "Desenvolvimento por trás da nuca no Smith",
  "0748": "Supino reto no Smith",
  "0749": "Bom-dia com joelhos flexionados no Smith",
  "1359": "Remada curvada no Smith",
  "0750": "Agachamento até o banco no Smith",
  "0751": "Supino fechado no Smith",
  "0752": "Levantamento terra no Smith",
  "0753": "Supino declinado no Smith",
  "0754": "Supino declinado com pegada inversa no Smith",
  "1433": "Agachamento frontal com pegada de arremesso no Smith",
  "3281": "Agachamento completo no Smith",
  "0755": "Agachamento hack no Smith",
  "0756": "Elevação de quadril no Smith",
  "0757": "Supino inclinado no Smith",
  "0758": "Supino inclinado com pegada inversa no Smith",
  "0759": "Elevação escapular no banco inclinado no Smith",
  "0760": "Leg press no Smith",
  "1434": "Agachamento com barra baixa no Smith",
  "1683": "Rosca bíceps no Smith",
  "1625": "Supino declinado fechado no Smith",
  "1752": "Extensão de tríceps inclinada no Smith",
  "1626": "Supino declinado com pegada inversa e fechada no Smith",
  "0761": "Remada com pegada fechada no Smith",
  "1360": "Remada unilateral no Smith",
  "1393": "Elevação de panturrilha unilateral no chão no Smith",
  "0762": "Remada para deltoide posterior no Smith",
  "0763": "Elevação da ponta dos pés no Smith",
  "1394": "Elevação da ponta dos pés no Smith",
  "1361": "Remada curvada com pegada inversa no Smith",
  "0764": "Supino com pegada inversa no Smith",
  "1395": "Elevação de panturrilha unilateral sentada no Smith",
  "0765": "Desenvolvimento de ombros sentado no Smith",
  "1426": "Rosca de punho sentada no Smith",
  "0766": "Desenvolvimento de ombros no Smith",
  "0767": "Encolhimento no Smith",
  "0768": "Afundo unilateral no Smith",
  "0769": "Afundo do velocista no Smith",
  "0770": "Agachamento no Smith",
  "0771": "Rosca de punho em pé com barra atrás no Smith",
  "0772": "Desenvolvimento militar em pé por trás da nuca no Smith",
  "0773": "Elevação de panturrilhas em pé no Smith",
  "0774": "Desenvolvimento militar em pé no Smith",
  "3142": "Agachamento sumô no Smith",
  "1396": "Elevação da ponta dos pés no Smith",
  "0775": "Remada alta no Smith",
  "1308": "Supino com pegada aberta no Smith",
  "1309": "Supino declinado com pegada aberta no Smith",
  "0776": "Puxada de arranco",
  "0777": "Rotação diagonal com halter",
  "1362": "Postura da esfinge",
  "0778": "Flexão aranha com deslocamento",
  "1363": "Alongamento da coluna",
  "2329": "Rotação da coluna",
  "2368": "Afundo estático",
  "0786": "Arremesso em agachamento",
  "1705": "Agachamento no BOSU",
  "1685": "Agachamento com alcance acima da cabeça",
  "1686": "Agachamento com alcance acima da cabeça e rotação",
  "2297": "Abdominal na bola suíça em amplitude completa com mãos atrás da cabeça",
  "3291": "Elevação Stalder",
  "3669": "Arqueiro em pé",
  "0788": "Desenvolvimento em pé por trás da nuca",
  "1490": "Elevação de panturrilhas em pé no degrau",
  "1397": "Elevação de panturrilhas em pé",
  "1398": "Alongamento de panturrilhas em pé",
  "1599": "Alongamento de posteriores e panturrilhas em pé com faixa",
  "0794": "Alongamento lateral em pé",
  "1364": "Inclinação pélvica em pé",
  "0795": "Flexão unilateral de joelho em pé",
  "0796": "Extensão com roda abdominal em pé",
  "3223": "Salto estrela (masculino)",
  "2138": "Pedalada na bicicleta ergométrica — variação 3",
  "0798": "Pedalada leve na bicicleta ergométrica",
  "3314": "Maltês com pernas afastadas",
  "3298": "Prancha com pernas afastadas",
  "1427": "Abdução de quadril com perna estendida",
  "0803": "Flexão de braços com elevação alternada do braço e da perna opostos",
  "0805": "Extensão abdominal no suspensor",
  "0806": "Flexão de braços suspensa",
  "0807": "Abdominal reverso suspenso",
  "0808": "Remada suspensa",
  "0809": "Afundo suspenso",
  "3433": "Batimento de pernas do nadador — variação 2 (masculino)",
  "3318": "Balanço em 360°",
  "1753": "Mergulho em três bancos",
  "2459": "Virada de pneu",
  "0811": "Levantamento terra com barra hexagonal",
  "0814": "Mergulho para tríceps",
  "0812": "Mergulho no banco com pernas apoiadas",
  "0813": "Mergulho entre bancos",
  "0815": "Mergulho para tríceps no chão",
  "0816": "Flexão de tríceps",
  "0817": "Alongamento de tríceps",
  "0871": "Abdominal grupado",
  "0818": "Puxada alta com pegada paralela em manopla dupla",
  "1466": "Elevação de quadril com rotação",
  "2802": "Elevação de pernas com rotação",
  "2801": "Elevação de pernas com rotação (feminino)",
  "3231": "Toque simultâneo nos pés (masculino)",
  "1365": "Alongamento da parte superior das costas",
  "1366": "Postura do cachorro olhando para cima",
  "3420": "Abdominal em V no chão",
  "0826": "Elevação vertical de pernas nas paralelas",
  "2141": "Caminhada no elíptico",
  "3655": "Passada andando com elevação dos joelhos",
  "1460": "Passada andando",
  "3666": "Caminhada na esteira inclinada",
  "2311": "Caminhada no simulador de escada",
  "0830": "Mergulho no banco com carga",
  "2987": "Barra fixa supinada com pegada fechada e carga na estação de paralelas",
  "3643": "Agachamento cossaco com carga (masculino)",
  "0832": "Abdominal curto com carga",
  "3670": "Abdominal declinado com carga",
  "0833": "Elevação de panturrilhas tipo burrinho com carga",
  "1310": "Flexão pliométrica com troca de apoio e carga",
  "2135": "Prancha frontal com carga",
  "0834": "Elevação frontal com carga",
  "0866": "Elevação de pernas e quadril suspensa com carga",
  "0835": "Hiperextensão na bola suíça com carga",
  "3641": "Subida ajoelhada com balanço e carga",
  "3644": "Avanço com balanço e carga",
  "3286": "Subida de força com carga",
  "3312": "Subida de força na barra com carga",
  "3290": "Barra fixa unilateral com carga",
  "0840": "Abdominal acima da cabeça na bola suíça com carga",
  "0841": "Barra fixa pronada com carga",
  "0844": "Elevação lateral dos braços com carga",
  "0846": "Abdominal russo com carga",
  "0845": "Abdominal russo com pernas elevadas e carga",
  "2371": "Abdominal russo com carga — variação 2",
  "0847": "Rosca bíceps sentada na bola suíça com carga",
  "0849": "Rotação de tronco sentada na bola suíça com carga",
  "0850": "Flexão lateral do tronco na bola suíça com carga",
  "0851": "Agachamento sissy com carga",
  "0852": "Agachamento com carga",
  "0853": "Rosca direta em pé com carga",
  "0854": "Aperto de mãos em pé com carga",
  "3313": "Mergulho na barra reta com carga",
  "3642": "Avanço com alongamento e carga",
  "0856": "Supino Svend com carga",
  "1754": "Mergulho em três bancos com carga",
  "1755": "Mergulho para tríceps com carga",
  "1767": "Mergulho para tríceps nas paralelas altas com carga",
  "0857": "Extensão com roda abdominal",
  "3637": "Extensão dinâmica com roda abdominal",
  "1429": "Barra fixa com pegada aberta",
  "1367": "Barra fixa por trás da nuca com pegada aberta",
  "1311": "Flexão de braços com mãos afastadas",
  "2363": "Mergulho para peitoral com pegada aberta nas paralelas altas",
  "0858": "Tiros de velocidade",
  "1604": "O maior alongamento do mundo",
  "1428": "Círculos com os punhos",
  "0859": "Enrolamento de punho com rolo de carga",
};
