// pt-BR — exercícios 884–1103 do EXDB
export default {
  "0530": "Moinho com dois kettlebells",
  "0531": "Supino unilateral no chão com kettlebell e amplitude ampliada",
  "0532": "Movimento em oito com kettlebell",
  "0533": "Agachamento frontal com kettlebell",
  "0534": "Agachamento taça com kettlebell",
  "0535": "Elevação ao ombro a partir da suspensão com kettlebell",
  "0536": "Afundo com passagem do kettlebell entre as pernas",
  "0537": "Arremesso unilateral completo com kettlebell",
  "1298": "Supino unilateral no chão com kettlebell",
  "0538": "Impulso unilateral acima da cabeça com kettlebell",
  "0539": "Desenvolvimento militar unilateral com inclinação lateral e kettlebell",
  "0540": "Desenvolvimento unilateral com impulso e kettlebell",
  "0541": "Remada unilateral com kettlebell",
  "0542": "Arranco unilateral com kettlebell",
  "0543": "Desenvolvimento unilateral acima da cabeça com kettlebell",
  "0544": "Agachamento pistola com kettlebell",
  "0545": "Flexão pliométrica com kettlebell",
  "0546": "Desenvolvimento sentado com kettlebell",
  "1438": "Desenvolvimento militar sentado com dois kettlebells",
  "0547": "Desenvolvimento alternado com kettlebells",
  "0548": "Puxada alta sumô com kettlebell",
  "0549": "Balanço com kettlebell",
  "0550": "Agachamento com desenvolvimento acima da cabeça e kettlebell",
  "0551": "Levantada turca com kettlebell, estilo agachamento",
  "0552": "Elevação aos ombros com dois kettlebells",
  "0553": "Desenvolvimento militar com dois kettlebells",
  "1345": "Remada com dois kettlebells",
  "0554": "Moinho com kettlebell",
  "0555": "Abdominal sentado com extensão das pernas",
  "0558": "Subida completa na barra com balanço",
  "3640": "Abdominal cruzado com toque no joelho",
  "1420": "Agachamento com salto partindo de joelhos",
  "1346": "Alongamento de dorsais ajoelhado",
  "3239": "Prancha ajoelhada com toque nos ombros (masculino)",
  "3211": "Flexão de braços com joelhos apoiados (masculino)",
  "3288": "Mergulho coreano",
  "3418": "Barra fixa em L",
  "3419": "Isometria em L no chão",
  "0562": "Rotação de 180° com barra ancorada",
  "3237": "Elevação lateral com barra ancorada",
  "3300": "Prancha inclinada à frente",
  "2271": "Gancho de esquerda no boxe",
  "0570": "Abdominal com recolhimento das pernas no banco reto",
  "1576": "Alongamento de posteriores com a perna elevada",
  "2287": "Leg press articulado alternado",
  "0571": "Remada baixa articulada alternada com pegada fechada",
  "0572": "Barra fixa supinada assistida na máquina",
  "0573": "Extensão lombar na máquina articulada",
  "0574": "Remada curvada na máquina articulada",
  "3200": "Remada curvada articulada com barra V",
  "0575": "Rosca direta na máquina articulada",
  "2289": "Elevação de panturrilhas na máquina articulada",
  "0577": "Supino na máquina articulada",
  "0576": "Supino na máquina articulada",
  "0578": "Levantamento terra na máquina articulada",
  "1300": "Supino declinado na máquina articulada",
  "1253": "Panturrilha burrinho na máquina articulada",
  "0579": "Puxada frontal na máquina articulada",
  "0580": "Encolhimento sem pegada na máquina articulada",
  "1439": "Encolhimento sem pegada na máquina articulada — versão 2",
  "2288": "Fortalecimento da pegada na máquina articulada",
  "1615": "Rosca Scott martelo na máquina articulada",
  "0581": "Remada alta na máquina articulada",
  "2286": "Extensão de quadril na máquina articulada — versão 2",
  "2611": "Leg press horizontal unilateral na máquina articulada",
  "1299": "Supino inclinado na máquina articulada",
  "1479": "Supino inclinado na máquina articulada — versão 2",
  "0582": "Flexão de joelho ajoelhado na máquina articulada",
  "0583": "Rotação de tronco ajoelhado na máquina articulada",
  "0584": "Elevação lateral na máquina articulada",
  "0585": "Cadeira extensora articulada",
  "0586": "Mesa flexora articulada",
  "3195": "Mesa flexora 2–1 na máquina articulada",
  "0587": "Desenvolvimento militar na máquina articulada",
  "0588": "Remada baixa com pegada fechada na máquina articulada",
  "0589": "Remada curvada unilateral na máquina articulada",
  "1356": "Remada alta lateral unilateral na máquina articulada",
  "1347": "Puxada aberta unilateral na máquina articulada",
  "0590": "Desenvolvimento unilateral de ombro na máquina articulada",
  "0591": "Mergulho para tríceps com pegada pronada na máquina articulada",
  "0592": "Rosca Scott na máquina articulada",
  "1614": "Rosca Scott na máquina articulada — versão 2",
  "2285": "Pulôver na máquina articulada",
  "2736": "Puxada lateral com pegada supinada na máquina articulada",
  "1616": "Rosca Scott com pegada pronada na máquina articulada",
  "1348": "Remada vertical com pegada inversa na máquina articulada",
  "0593": "Hiperextensão reversa na máquina articulada",
  "1349": "Remada T com pegada invertida na máquina articulada",
  "2315": "Panturrilha rotativa na máquina articulada",
  "2335": "Flexão plantar sentada na máquina articulada",
  "0594": "Elevação de panturrilhas sentada na máquina articulada",
  "1452": "Abdominal sentado na máquina articulada",
  "0595": "Abdominal sentado com apoio peitoral na máquina articulada",
  "3760": "Abdominal sentado na máquina articulada — versão 2",
  "1451": "Mergulho sentado na máquina articulada",
  "0596": "Crucifixo sentado na máquina articulada",
  "3759": "Inclinação de tronco sentada na máquina articulada",
  "0597": "Cadeira abdutora articulada",
  "0598": "Cadeira adutora articulada",
  "0599": "Cadeira flexora articulada",
  "0600": "Abdominal sentado com elevação das pernas na máquina articulada",
  "0602": "Crucifixo inverso sentado na máquina articulada",
  "0601": "Crucifixo inverso sentado com pegada neutra na máquina articulada",
  "1350": "Remada sentada na máquina articulada",
  "1385": "Elevação de panturrilhas em agachamento no leg press articulado",
  "0603": "Desenvolvimento de ombros na máquina articulada",
  "0869": "Desenvolvimento de ombros na máquina articulada — versão 2",
  "2318": "Desenvolvimento de ombros na máquina articulada — versão 3",
  "0604": "Encolhimento de ombros na máquina articulada",
  "0605": "Elevação de panturrilhas em pé na máquina articulada",
  "3758": "Supino em pé na máquina articulada",
  "0606": "Remada T na máquina articulada",
  "1351": "Remada T com pegada supinada na máquina articulada",
  "0607": "Extensão de tríceps na máquina articulada",
  "1313": "Remada unilateral na máquina articulada",
  "0609": "Ponte de Londres com corda",
  "3013": "Ponte baixa de glúteos no chão",
  "1352": "Flexão lombar",
  "3582": "Afundo com salto",
  "1688": "Afundo com rotação de tronco",
  "0613": "Alongamento lateral de quadríceps deitado",
  "2312": "Abdominal deitado com cotovelo no joelho",
  "0620": "Elevação de pernas deitado no banco reto",
  "0865": "Elevação de pernas e quadril deitado",
  "1301": "Supino na máquina com foco na parte interna do peitoral",
  "0624": "Cadeira isométrica na parede com marcha",
  "1353": "Recepção e arremesso acima da cabeça com bola medicinal",
  "1302": "Passe de peito com bola medicinal",
  "1303": "Arremesso de peito com bola medicinal em apoio de três pontos",
  "1304": "Arremessos de peito consecutivos com bola medicinal",
  "1305": "Arremesso único de peito com bola medicinal",
  "1312": "Arremesso de peito com bola medicinal seguido de corrida",
  "1701": "Flexão de braços com pegada fechada na bola medicinal",
  "1354": "Arremesso ao chão acima da cabeça com bola medicinal",
  "1750": "Arremesso de peito deitado com bola medicinal",
  "0627": "Barra fixa com pegada mista",
  "3217": "Flexão hindu modificada (masculino)",
  "1421": "Flexão modificada descendo aos antebraços",
  "0628": "Caminhada lateral em agachamento",
  "0630": "Escalador",
  "0631": "Subida completa na barra",
  "1401": "Subida completa na barra vertical",
  "2328": "Flexão fechada na bola suíça",
  "1403": "Alongamento lateral do pescoço",
  "0634": "Abdominal negativo",
  "1495": "Abdominal oblíquo — versão 2",
  "0635": "Abdominal oblíquo no chão",
  "0636": "Rosca martelo com barra olímpica",
  "0637": "Extensão de tríceps com barra olímpica",
  "1355": "Isometria unilateral de dorsal contra a parede",
  "0638": "Barra fixa supinada unilateral",
  "0639": "Mergulho unilateral",
  "0640": "Arremesso unilateral da bola medicinal ao chão",
  "1773": "Remada unilateral com toalha",
  "1386": "Panturrilha burrinho unilateral",
  "1387": "Elevação de panturrilha unilateral no chão",
  "1476": "Agachamento unilateral",
  "0641": "Abdominal Otis",
  "0642": "Flexão com chute da perna para fora",
  "0643": "Alongamento de tríceps acima da cabeça",
  "3147": "Inclinação pélvica",
  "1422": "Inclinação pélvica seguida de ponte",
  "1388": "Alongamento dos fibulares",
  "3662": "Flexão do V invertido à cobra",
  "1306": "Flexão pliométrica",
  "1687": "Passo para trás com alcance acima da cabeça",
  "1389": "Alongamento do tibial posterior",
  "3119": "Agachamento profundo",
  "3132": "Agachamento profundo com apoio",
  "0648": "Elevação explosiva da barra aos ombros",
  "3665": "Prancha alternando mãos e antebraços",
  "3203": "Meio abdominal com as mãos atrás da cabeça (masculino)",
  "1707": "Rotação de tronco de bruços na bola suíça",
  "0651": "Barra fixa com pegada neutra",
  "0650": "Recolhimento dos joelhos na bola suíça",
  "0652": "Barra fixa",
  "1689": "Empurrar e puxar com o peso corporal",
  "3638": "Flexão seguida de corrida estacionária em prancha",
  "1307": "Flexão de braços no BOSU",
  "0662": "Flexão de braços",
  "0653": "Flexão de braços no BOSU",
  "0655": "Flexão de braços na bola suíça",
  "0656": "Flexão de braços na bola suíça",
  "0659": "Flexão de braços na parede",
  "0658": "Flexão de braços na parede — versão 2",
  "0660": "Flexão fechada com apoio no halter",
  "0661": "Flexão com chute da perna para dentro",
  "0663": "Flexão de braços na bola medicinal",
  "1467": "Flexão apoiada nos antebraços",
  "3145": "Flexão de braços com protração escapular",
  "0664": "Flexão com transição para prancha lateral",
  "3533": "Agachamento para quadríceps",
  "3201": "Abdominal curto de um quarto",
  "3552": "Passos rápidos no lugar — versão 2",
  "0666": "Flexão com um braço elevado lateralmente",
  "0668": "Ponte de glúteos declinada",
  "0669": "Alongamento do deltoide posterior",
  "0670": "Barra fixa por trás da cabeça",
  "1582": "Alongamento reclinado da perna com corda",
  "3236": "Elevação de quadril ajoelhada com faixa elástica (feminino)",
  "3007": "Extensão de joelhos com faixa elástica",
  "3123": "Rosca bíceps sentada com faixa elástica",
  "3124": "Supino sentado com faixa elástica",
  "3006": "Abdução de quadril sentada com faixa elástica",
  "3122": "Desenvolvimento de ombros sentado com faixa elástica",
  "3144": "Remada sentada com tronco ereto e faixa elástica",
  "0872": "Abdominal reverso",
  "0672": "Mergulho reverso",
  "0673": "Puxada frontal na máquina com pegada supinada",
  "0674": "Barra fixa com pegada supinada",
  "0675": "Hiperextensão reversa na bola suíça",
  "1423": "Hiperextensão reversa no banco reto",
  "3663": "Prancha reversa com elevação de perna",
  "0677": "Mergulho nas argolas",
  "2571": "Alongamento sapinho com balanço",
  "0678": "Barra fixa Rocky com puxada",
  "2208": "Alongamento das costas com rolo de espuma",
  "2204": "Prancha serrote no rolo de espuma",
  "2205": "Alongamento lateral do quadril com rolo de espuma",
  "2202": "Alongamento do quadril com rolo de espuma",
};
