// pt-BR — nomes naturais dos exercícios em EXDB[0..220].
export default {
  "0001": "Abdominal 3/4",
  "0002": "Flexão lateral a 45°",
  "0003": "Abdominal bicicleta",
  "1512": "Alongamento de quadríceps em quatro apoios",
  "0006": "Toque alternado nos calcanhares",
  "0007": "Puxada lateral alternada na polia",
  "1368": "Círculos com os tornozelos",
  "3293": "Barra fixa arqueiro",
  "3294": "Flexão arqueiro",
  "2355": "Elevação de joelhos suspensa",
  "2333": "Elevação de pernas estendidas suspensa",
  "3214": "Toque circular nos pés com braços abertos (masculino)",
  "3204": "Abdominal completo com braços acima da cabeça (masculino)",
  "0009": "Mergulho para peito assistido (ajoelhado)",
  "0011": "Elevação de joelhos suspensa assistida",
  "0010": "Elevação de joelhos suspensa assistida com lançamento para baixo",
  "1708": "Alongamento assistido de panturrilhas deitado",
  "1709": "Alongamento assistido de glúteos deitado",
  "1710": "Alongamento assistido de glúteo e piriforme deitado",
  "0012": "Elevação de pernas deitado assistida com lançamento lateral",
  "0013": "Elevação de pernas deitado assistida com lançamento para baixo",
  "0014": "Rotação russa assistida",
  "0015": "Barra fixa assistida com pegada neutra fechada",
  "0016": "Extensão de quadril deitado de bruços com assistência",
  "1713": "Alongamento assistido de quadríceps deitado de bruços",
  "1714": "Alongamento assistido do reto femoral deitado de bruços",
  "0017": "Barra fixa pronada assistida",
  "1716": "Alongamento assistido do peitoral maior sentado na bola suíça",
  "1712": "Alongamento assistido de adutores deitado de lado",
  "1758": "Abdominal assistido",
  "1431": "Barra fixa supinada assistida em pé",
  "1432": "Barra fixa pronada assistida em pé",
  "0018": "Extensão de tríceps em pé assistida com toalha",
  "0019": "Mergulho de tríceps assistido (ajoelhado)",
  "2364": "Mergulho para peito assistido com pegada aberta (ajoelhado)",
  "3220": "Salto com afastamento de pernas (masculino)",
  "3672": "Passo alternado à frente e atrás",
  "1314": "Extensão lombar na bola suíça",
  "3297": "Alavanca dorsal",
  "1405": "Alongamento de costas e peitoral",
  "1473": "Salto para trás",
  "0020": "Prancha de equilíbrio",
  "0968": "Rosca bíceps alternada com faixa elástica",
  "0969": "Abdominal V alternado com faixa elástica",
  "0970": "Barra fixa assistida com faixa elástica",
  "0971": "Abdominal com roda assistido por faixa elástica",
  "1254": "Supino reto com faixa elástica",
  "0980": "Extensão de quadril inclinada com faixa elástica",
  "0972": "Abdominal bicicleta com faixa elástica",
  "0974": "Puxada com pegada fechada e faixa elástica",
  "0975": "Flexão com pegada fechada e faixa elástica",
  "0976": "Rosca concentrada com faixa elástica",
  "3117": "Puxada fechada com costas apoiadas e faixa elástica",
  "3116": "Puxada supinada com costas apoiadas e faixa elástica",
  "0977": "Elevação frontal-lateral com faixa elástica",
  "0978": "Elevação frontal com faixa elástica",
  "1408": "Elevação de quadril com faixa elástica",
  "0979": "Press Pallof horizontal com faixa elástica",
  "0981": "Abdominal canivete com faixa elástica",
  "0983": "Puxada unilateral ajoelhada com faixa elástica",
  "0985": "Abdominal ajoelhado com rotação e faixa elástica",
  "0984": "Rotação interna de quadril deitado com faixa elástica",
  "1002": "Elevação de pernas estendidas deitado com faixa elástica",
  "0986": "Rosca bíceps unilateral acima da cabeça com faixa elástica",
  "0987": "Agachamento búlgaro unilateral com faixa elástica",
  "0988": "Remada baixa unilateral em pé com faixa elástica",
  "0989": "Supino unilateral com rotação e faixa elástica",
  "0990": "Remada sentada unilateral com rotação e faixa elástica",
  "0991": "Extensão de quadril com faixa elástica entre as pernas",
  "0992": "Abdominal com extensão dos braços e faixa elástica",
  "0993": "Crucifixo inverso com faixa elástica",
  "0994": "Rosca de punho inversa com faixa elástica",
  "0996": "Rotação interna de quadril sentado com faixa elástica",
  "1011": "Rotação de tronco sentada com faixa elástica",
  "0997": "Desenvolvimento de ombros com faixa elástica",
  "1018": "Encolhimento de ombros com faixa elástica",
  "0998": "Extensão lateral de tríceps com faixa elástica",
  "0999": "Elevação de panturrilha unilateral com faixa elástica",
  "1000": "Elevação tibial unilateral com faixa elástica",
  "1001": "Afundo com faixa elástica",
  "1004": "Agachamento com faixa elástica",
  "1003": "Agachamento com remada e faixa elástica",
  "1005": "Abdominal em pé com faixa elástica",
  "1022": "Remada em pé para deltoide posterior com faixa elástica",
  "1007": "Abdominal em pé com rotação e faixa elástica",
  "1008": "Subida no banco com faixa elástica",
  "1009": "Levantamento terra com pernas rígidas e faixa elástica",
  "1023": "Levantamento terra com pernas rígidas e costas retas com faixa elástica",
  "1010": "Levantamento terra com pernas estendidas e faixa elástica",
  "1012": "Desenvolvimento acima da cabeça com rotação e faixa elástica",
  "1369": "Elevação de panturrilhas com faixa elástica sob os dois pés — versão 2",
  "1013": "Puxada supinada com faixa elástica",
  "1014": "Abdominal V com faixa elástica",
  "1015": "Press Pallof vertical com faixa elástica",
  "1016": "Rosca de punho com faixa elástica",
  "1017": "Elevação em Y com faixa elástica",
  "0023": "Rosca bíceps alternada com barra",
  "0024": "Agachamento frontal com barra e banco",
  "0025": "Supino reto com barra",
  "0026": "Agachamento no banco com barra",
  "1316": "Pullover com barra e braços flexionados",
  "0027": "Remada curvada com barra",
  "2407": "Rosca bíceps com barra e suporte para braços",
  "0028": "Levantamento ao peito e desenvolvimento com barra",
  "0029": "Agachamento frontal com barra em pegada olímpica",
  "0030": "Supino fechado com barra",
  "0031": "Rosca direta com barra",
  "0032": "Levantamento terra com barra",
  "0033": "Supino declinado com barra",
  "0034": "Pullover declinado com barra e braços flexionados",
  "0035": "Tríceps testa declinado com barra e pegada fechada",
  "1255": "Pullover declinado com barra",
  "0036": "Supino declinado com pegada aberta e barra",
  "0037": "Pullover declinado com pegada aberta e barra",
  "0038": "Rosca arrastada com barra",
  "1370": "Elevação de panturrilhas no chão com barra",
  "0039": "Agachamento frontal com barra ao peito",
  "0041": "Elevação frontal com barra",
  "0040": "Elevação frontal seguida de pullover com barra",
  "0042": "Agachamento frontal com barra",
  "0043": "Agachamento completo com barra",
  "1461": "Agachamento completo com barra (vista traseira)",
  "1462": "Agachamento completo com barra (vista lateral)",
  "1545": "Agachamento Zercher completo com barra",
  "1409": "Ponte de glúteos com barra",
  "3562": "Ponte de glúteos com barra e pés no banco (masculino)",
  "0044": "Bom dia com barra",
  "0045": "Supino guilhotina com barra",
  "0046": "Agachamento hack com barra",
  "1436": "Agachamento com barra alta",
  "0047": "Supino inclinado com barra",
  "1719": "Supino inclinado fechado com barra",
  "0048": "Supino inclinado com pegada supinada e barra",
  "0049": "Remada no banco inclinado com barra",
  "0050": "Desenvolvimento inclinado de ombros com barra",
  "0051": "Agachamento Jefferson com barra",
  "0052": "Supino JM com barra",
  "0053": "Agachamento com salto e barra",
  "1410": "Afundo lateral com barra",
  "1435": "Agachamento com barra baixa",
  "0054": "Afundo com barra",
  "1720": "Extensão de tríceps deitado com barra atrás da cabeça",
  "0055": "Supino fechado deitado com barra",
  "0056": "Tríceps testa deitado com pegada fechada e barra",
  "0057": "Extensão de tríceps deitado com barra",
  "0058": "Elevação pélvica deitada com barra",
  "0059": "Rosca Scott deitado com barra",
  "0061": "Extensão de tríceps deitado com barra",
  "0060": "Tríceps testa deitado com barra",
  "0063": "Agachamento com base fechada e barra",
  "0064": "Remada curvada unilateral com barra",
  "0065": "Supino unilateral no chão com barra",
  "0066": "Levantamento terra lateral unilateral com barra",
  "0067": "Arranco unilateral com barra",
  "0068": "Agachamento unilateral com barra",
  "0069": "Agachamento acima da cabeça com barra",
  "1411": "Rosca de punho pronada com barra no banco",
  "1412": "Rosca de punho supinada com barra no banco",
  "3017": "Remada Pendlay com barra",
  "1751": "Supino a partir dos pinos com barra",
  "0070": "Rosca Scott com barra",
  "0071": "Abdominal com barra no peito",
  "0072": "Rosca de bíceps deitado de bruços no banco inclinado com barra",
  "0073": "Pullover com barra",
  "0022": "Pullover seguido de supino com barra",
  "0074": "Levantamento terra parcial no rack com barra",
  "0075": "Elevação posterior para deltoides com barra",
  "0076": "Remada para deltoide posterior com barra",
  "0078": "Afundo para trás com barra",
  "0077": "Afundo para trás com barra — versão 2",
  "0079": "Rosca de punho inversa com barra — versão 2",
  "2187": "Supino fechado com pegada supinada e barra",
  "0080": "Rosca inversa com barra",
  "0118": "Remada curvada com pegada supinada e barra",
  "1256": "Supino declinado com pegada supinada e barra",
  "1257": "Supino inclinado com pegada supinada e barra",
  "1317": "Remada no banco inclinado com pegada supinada e barra",
  "1721": "Tríceps testa com pegada supinada e barra",
  "0081": "Rosca Scott inversa com barra",
  "0082": "Rosca de punho inversa com barra",
  "0084": "Abdominal com rolamento de barra",
  "0083": "Abdominal com rolamento de barra a partir do banco",
  "0085": "Levantamento terra romeno com barra",
  "0086": "Desenvolvimento militar sentado por trás da cabeça com barra",
  "0087": "Desenvolvimento Bradford sentado com barra",
  "0088": "Elevação de panturrilhas sentado com barra",
  "1371": "Elevação de panturrilhas sentado com barra",
  "1718": "Extensão de tríceps sentada com pegada fechada atrás da nuca e barra",
  "0089": "Rosca concentrada sentada com pegada fechada e barra",
  "0090": "Bom dia sentado com barra",
  "0091": "Desenvolvimento acima da cabeça sentado com barra",
  "0092": "Extensão de tríceps acima da cabeça sentado com barra",
  "0094": "Rotação de tronco sentada com barra",
  "0095": "Encolhimento de ombros com barra",
  "0096": "Flexão lateral com barra — versão 2",
  "0098": "Agachamento com base ampla e barra",
  "0097": "Agachamento lateral com barra — versão 2",
  "1756": "Levantamento terra unilateral com barra",
  "0099": "Afundo unilateral com barra",
  "2799": "Elevação alternada de pernas sentada com barra",
  "2800": "Elevação alternada de pernas sentada com barra (feminino)",
  "0100": "Puxada esquiador com barra",
  "0101": "Agachamento explosivo com barra",
  "2810": "Afundo com barra — versão 2",
  "0102": "Agachamento ajoelhado com barra",
  "2798": "Agachamento com salto, passo e afundo para trás com barra",
  "0103": "Abdominal em pé com rolamento de barra",
  "0104": "Rosca de punho em pé com barra atrás do corpo",
  "0105": "Desenvolvimento Bradford em pé com barra",
  "1372": "Elevação de panturrilhas em pé com barra",
  "0106": "Rosca direta em pé com pegada fechada e barra",
  "1456": "Desenvolvimento militar em pé com pegada fechada e barra",
  "2414": "Rosca concentrada unilateral em pé com barra",
  "0107": "Elevação frontal acima da cabeça em pé com barra",
  "0108": "Elevação de panturrilhas em pé com barra",
  "0109": "Extensão de tríceps acima da cabeça em pé com barra",
  "0110": "Rosca inversa em pé com barra",
  "0111": "Elevação de panturrilhas com balanço em pé e barra",
  "0112": "Rotação de tronco em pé com barra",
  "1629": "Rosca bíceps em pé com pegada aberta e barra",
  "1457": "Desenvolvimento militar em pé com pegada aberta e barra"
};
