// pt-BR — nomes naturais dos exercícios em EXDB[221..441].
export default {
  "0113": "Rosca direta em pé com barra e pegada aberta",
  "0114": "Subida no banco com barra",
  "0115": "Bom-dia com barra e pernas semirrígidas",
  "0116": "Levantamento terra com barra e pernas estendidas",
  "0117": "Levantamento terra sumô com barra",
  "3305": "Agachamento com desenvolvimento com barra",
  "0120": "Remada alta com barra",
  "0119": "Remada alta com barra (versão 2)",
  "0121": "Remada alta com barra (versão 3)",
  "0122": "Supino com barra e pegada aberta",
  "1258": "Supino com barra, pegada supinada e aberta",
  "0124": "Agachamento com barra e base aberta",
  "0123": "Remada alta com barra e pegada aberta",
  "0126": "Flexão de punhos com barra",
  "0125": "Flexão de punhos com barra (versão 2)",
  "0127": "Agachamento Zercher com barra",
  "3212": "Toque básico nos pés (masculino)",
  "0128": "Ondulação com corda naval",
  "3360": "Caminhada do urso",
  "1259": "Alongamento de peitoral com as mãos atrás da cabeça",
  "0129": "Mergulho no banco com joelhos flexionados",
  "1399": "Mergulho no banco com os pés no chão",
  "0130": "Extensão de quadril no banco",
  "3019": "Remada invertida com apoio no banco",
  "3639": "Rotação lombar deitado com joelhos flexionados (masculino)",
  "1770": "Rosca concentrada com apoio na perna",
  "0139": "Barra fixa supinada com pegada fechada para bíceps",
  "0140": "Barra fixa pronada para bíceps",
  "0137": "Extensão de tríceps em apoio elevado",
  "3543": "Agachamento com salto e aproximação dos pés",
  "3544": "Prancha lateral inclinada com peso corporal",
  "1771": "Extensão de tríceps ajoelhado com peso corporal",
  "1769": "Rosca de bíceps deitado de lado com peso corporal",
  "3168": "Remada com agachamento e peso corporal",
  "3167": "Remada com agachamento e peso corporal usando toalha",
  "1373": "Elevação de panturrilhas em pé com peso corporal",
  "3156": "Remada unilateral em pé com peso corporal e pegada fechada",
  "3158": "Remada em pé com peso corporal e pegada fechada",
  "3162": "Remada unilateral em pé com peso corporal",
  "3161": "Remada unilateral em pé com peso corporal usando toalha",
  "3166": "Remada em pé com peso corporal",
  "3165": "Remada em pé com peso corporal usando toalha",
  "0138": "Elevação reversa de quadril",
  "1374": "Salto na caixa com estabilização unilateral na descida",
  "2466": "Ponte com escalador cruzado",
  "1160": "Agachamento com apoio, flexão e salto",
  "0870": "Elevação de quadril para abdômen",
  "1494": "Postura da borboleta",
  "0148": "Desenvolvimento alternado de ombros na polia",
  "0149": "Extensão alternada de tríceps na polia",
  "3235": "Flexão inversa de joelhos assistida na polia",
  "0150": "Puxada lateral na polia com barra",
  "0151": "Supino na polia",
  "1630": "Rosca com pegada fechada na polia",
  "1631": "Rosca concentrada na polia",
  "0152": "Extensão concentrada de tríceps na polia com apoio no joelho",
  "0153": "Puxada lateral cruzada na polia",
  "0154": "Crucifixo inverso cruzado na polia",
  "0155": "Crucifixo cruzado na polia (variação)",
  "0868": "Rosca direta na polia",
  "0157": "Levantamento terra na polia",
  "0158": "Crucifixo declinado na polia",
  "1260": "Supino declinado unilateral na polia",
  "1261": "Supino declinado na polia",
  "0159": "Remada sentada declinada na polia com pegada aberta",
  "1632": "Rosca arrastada na polia",
  "0160": "Remada sentada no chão na polia com pegada aberta",
  "0161": "Elevação à frente na polia",
  "0162": "Elevação frontal na polia",
  "0164": "Elevação frontal de ombros na polia",
  "0165": "Rosca martelo na polia com corda",
  "1722": "Extensão de tríceps acima da cabeça na polia alta",
  "0167": "Remada alta ajoelhada na polia",
  "0168": "Adução de quadril na polia",
  "0169": "Supino inclinado na polia",
  "1318": "Remada no banco inclinado na polia",
  "0171": "Crucifixo inclinado na polia",
  "0170": "Crucifixo inclinado na polia sobre bola suíça",
  "0172": "Puxada inclinada de braços estendidos na polia",
  "0173": "Extensão inclinada de tríceps na polia",
  "0174": "Rotação de judô na polia",
  "0860": "Coice de tríceps na polia",
  "0175": "Abdominal ajoelhado na polia",
  "3697": "Remada ajoelhada para deltoide posterior na polia com corda (masculino)",
  "0176": "Extensão de tríceps ajoelhado na polia",
  "2330": "Puxada alta na polia com amplitude completa",
  "0177": "Puxada lateral na polia com corda",
  "2616": "Puxada lateral na polia com barra V",
  "0178": "Elevação lateral na polia",
  "0179": "Crucifixo de baixo para cima na polia",
  "0180": "Remada baixa sentada na polia",
  "1634": "Rosca de bíceps deitado na polia",
  "0182": "Rosca deitado na polia com pegada fechada",
  "0184": "Puxada de braços estendidos deitado na polia com corda",
  "0185": "Crucifixo deitado na polia",
  "0186": "Extensão de tríceps deitado na polia (versão 2)",
  "0188": "Crucifixo na altura média na polia",
  "0189": "Remada curvada unilateral na polia",
  "0190": "Rosca unilateral na polia",
  "1262": "Crucifixo declinado unilateral na polia",
  "1263": "Crucifixo unilateral na polia sobre bola suíça",
  "1264": "Crucifixo inclinado unilateral na polia sobre bola suíça",
  "1265": "Supino inclinado unilateral na polia",
  "1266": "Supino inclinado unilateral na polia sobre bola suíça",
  "0191": "Elevação lateral unilateral com tronco inclinado na polia",
  "0192": "Elevação lateral unilateral na polia",
  "1633": "Rosca unilateral no banco Scott na polia",
  "1267": "Supino unilateral na polia sobre bola suíça",
  "3563": "Puxada unilateral na polia",
  "1635": "Rosca inversa unilateral no banco Scott na polia",
  "0193": "Remada alta unilateral ajoelhada na polia com tronco reto",
  "1723": "Extensão unilateral de tríceps na polia",
  "1636": "Rosca acima da cabeça na polia",
  "1637": "Rosca acima da cabeça na polia sobre bola suíça",
  "0194": "Extensão de tríceps acima da cabeça na polia com corda",
  "1319": "Remada na polia com rotação das palmas",
  "0195": "Rosca no banco Scott na polia",
  "1268": "Supino na polia sobre bola suíça",
  "0196": "Extensão de quadril na polia com corda",
  "0198": "Puxada alta na polia",
  "0197": "Puxada alta na polia com barra para dorsais",
  "1638": "Rosca de bíceps na puxada alta",
  "0201": "Extensão de tríceps na polia",
  "0199": "Puxada de braços estendidos na polia (versão 2)",
  "0200": "Extensão de tríceps na polia com corda",
  "0202": "Remada para deltoide posterior na polia com pegadores",
  "0203": "Remada para deltoide posterior na polia com corda",
  "0204": "Extensão posterior de tríceps na polia",
  "0205": "Puxada alta posterior na polia",
  "0873": "Abdominal reverso na polia",
  "0206": "Rosca inversa na polia",
  "2406": "Extensão de tríceps na polia com pegada inversa, barra EZ e isolador de braços",
  "1413": "Rosca inversa unilateral na polia",
  "0209": "Rosca inversa no banco Scott na polia",
  "0210": "Extensão de punhos na polia",
  "0207": "Extensão de tríceps na polia com pegada inversa",
  "0208": "Remada alta sentada na polia, pegada inversa e tronco reto",
  "1320": "Remada sentada cruzada na polia com corda",
  "1321": "Remada sentada elevada na polia com corda",
  "1322": "Remada no banco inclinado na polia com corda e braços estendidos",
  "1639": "Rosca martelo no banco Scott na polia com corda",
  "1724": "Extensão de tríceps acima da cabeça na polia alta com corda",
  "1725": "Extensão inclinada de tríceps na polia com corda",
  "1726": "Extensão de tríceps deitado no chão na polia com corda",
  "1640": "Rosca martelo unilateral no banco Scott na polia com corda",
  "1323": "Remada sentada na polia com corda",
  "0211": "Rotação russa na polia sobre bola suíça",
  "2144": "Supino sentado na polia",
  "0212": "Abdominal sentado na polia",
  "1641": "Rosca sentada na polia",
  "0213": "Remada alta sentada na polia com barra V",
  "0214": "Remada alternada unilateral sentada na polia",
  "1642": "Rosca concentrada unilateral sentada na polia",
  "1643": "Rosca sentada acima da cabeça na polia",
  "0215": "Elevação lateral posterior sentada na polia",
  "0861": "Remada sentada na polia",
  "0216": "Rotação interna de ombro sentado na polia",
  "2399": "Rotação de tronco sentado na polia",
  "0218": "Remada sentada na polia com pegada aberta",
  "0219": "Desenvolvimento de ombros na polia",
  "0220": "Encolhimento de ombros na polia",
  "0222": "Inclinação lateral de tronco na polia",
  "0221": "Abdominal lateral na polia sobre BOSU",
  "0223": "Abdominal lateral na polia",
  "1717": "Agachamento com remada na polia e corda",
  "1644": "Rosca em agachamento na polia",
  "0224": "Flexão de punhos por trás do corpo em pé na polia",
  "1375": "Elevação de panturrilhas em pé na polia",
  "0225": "Crucifixo inverso alto cruzado em pé na polia",
  "0226": "Abdominal em pé na polia",
  "0874": "Abdominal em pé na polia com corda",
  "0227": "Crucifixo em pé na polia",
  "0228": "Extensão de quadril em pé na polia",
  "0229": "Rosca interna em pé na polia",
  "0230": "Elevação diagonal em pé na polia",
  "0231": "Extensão unilateral de tríceps em pé na polia",
  "1376": "Elevação unilateral de panturrilha em pé na polia",
  "0232": "Puxada em pé na polia com corda",
  "0233": "Remada em pé para deltoide posterior na polia com corda",
  "1727": "Extensão unilateral de tríceps acima da cabeça em pé na polia com pegada inversa",
  "0234": "Remada em pé na polia com barra V",
  "0235": "Rotação externa de ombro em pé na polia",
  "0236": "Remada com rotação de tronco em pé na polia com barra V",
  "1269": "Cruzamento de braços estendidos em pé na polia",
  "0238": "Puxada de braços estendidos na polia",
  "0237": "Puxada de braços estendidos na polia com corda",
  "0239": "Remada sentada na polia com tronco reto",
  "0240": "Crucifixo inverso deitado na polia",
  "2464": "Remada caiaque Thibaudeau na polia",
  "0241": "Extensão de tríceps na polia com barra V",
  "2405": "Extensão de tríceps na polia com barra V e isolador de braços",
  "0242": "Abdominal reverso com joelhos recolhidos na polia",
  "0243": "Rotação de tronco na polia",
  "0862": "Rotação de tronco de cima para baixo na polia",
  "0244": "Puxada com rotação de tronco na polia",
  "1645": "Rosca com os dois braços no banco inclinado na polia",
  "1728": "Coice de tríceps bilateral na polia",
  "0245": "Puxada alta supinada na polia",
  "1270": "Crucifixo cruzado para peitoral superior na polia",
  "1324": "Remada para a parte superior das costas na polia",
  "0246": "Remada alta na polia",
  "1325": "Puxada na polia atrás da nuca com pegada aberta",
  "0247": "Flexão de punhos na polia",
  "1407": "Alongamento de panturrilha empurrando a parede",
  "1377": "Alongamento de panturrilha com as mãos na parede",
  "1378": "Alongamento de panturrilha com corda",
  "0248": "Remada deitada com barra curvada",
  "2963": "Elevação de pernas estendidas na cadeira romana",
  "1548": "Alongamento de perna estendida na cadeira",
  "1271": "Alongamento de peitoral e parte anterior dos ombros",
  "0251": "Mergulho para peitoral",
  "1430": "Mergulho para peitoral na estação de paralelas e barra fixa",
  "2462": "Mergulho para peitoral na barra reta",
  "1272": "Alongamento de peitoral com bola suíça",
  "3216": "Flexão com toque no peito (masculino)",
  "1326": "Barra fixa supinada",
  "0253": "Barra fixa com pegada neutra fechada",
  "0257": "Círculos com os joelhos para alongamento",
  "1273": "Flexão com palmas",
  "0258": "Flexão tipo relógio",
  "1327": "Barra fixa supinada com pegada fechada"
};
