// pt-BR — nomes dos exercícios nos índices 442–662 da EXDB
export default {
  "0259": "Flexão com pegada fechada",
  "2398": "Flexão com pegada fechada e joelhos apoiados",
  "0260": "Abdominal casulo",
  "1468": "Toque nos pés com rotação na posição de caranguejo",
  "0262": "Abdominal cruzado",
  "0267": "Abdominal com braços acima da cabeça",
  "0271": "Abdominal na bola suíça",
  "0272": "Abdominal na bola suíça com braços estendidos",
  "0274": "Abdominal no chão",
  "3016": "Abdominal parcial",
  "3769": "Agachamento cruzado",
  "2331": "Elíptico",
  "0276": "Abdominal inseto morto",
  "0277": "Abdominal curto no banco declinado",
  "0279": "Flexão declinada",
  "0282": "Abdominal completo no banco declinado",
  "1274": "Flexão profunda",
  "0283": "Flexão diamante",
  "0284": "Elevação de panturrilhas burrinho",
  "1275": "Flexão com apoio dos joelhos na subida",
  "0285": "Rosca bíceps alternada com halteres",
  "2403": "Rosca bíceps alternada com halteres e suporte para braços",
  "1646": "Rosca martelo alternada no banco Scott com halteres",
  "1647": "Rosca alternada no banco Scott com halteres",
  "1648": "Rosca martelo alternada sentada com halteres",
  "0286": "Desenvolvimento alternado com halteres",
  "1649": "Rosca bíceps alternada com halteres e perna elevada na bola suíça",
  "1650": "Rosca bíceps alternada sentada na bola suíça com halteres",
  "2137": "Desenvolvimento Arnold com halteres",
  "0287": "Desenvolvimento Arnold com halteres, versão 2",
  "0288": "Pullover com halter",
  "0289": "Supino reto com halteres",
  "0290": "Desenvolvimento sentado no banco com halteres",
  "0291": "Agachamento no banco com halter",
  "0293": "Remada curvada com halteres",
  "1651": "Avanço com rosca bíceps e rotação de tronco com halteres",
  "1652": "Rosca bíceps com halteres na bola suíça e uma perna elevada",
  "1653": "Rosca bíceps com halteres em apoio unipodal",
  "0294": "Rosca bíceps com halteres",
  "2401": "Rosca bíceps com halteres e suporte para braços",
  "1654": "Rosca bíceps inversa com halteres",
  "1655": "Agachamento com rosca bíceps e halteres",
  "1656": "Rosca bíceps sentada em V no BOSU com halteres",
  "1201": "Burpee com halteres",
  "0295": "Levantamento ao ombro com halteres",
  "1731": "Supino com pegada fechada e halteres",
  "0296": "Supino reto com pegada fechada e halteres",
  "0297": "Rosca concentrada com halter",
  "3635": "Avanço à frente com halter no lado oposto",
  "0298": "Rosca martelo cruzada com halteres",
  "1657": "Rosca martelo cruzada com halteres, versão 2",
  "0299": "Desenvolvimento cubano com halteres",
  "2136": "Desenvolvimento cubano com halteres, versão 2",
  "0300": "Levantamento terra com halteres",
  "0301": "Supino declinado com halteres",
  "0302": "Crucifixo declinado com halteres",
  "0303": "Supino declinado com pegada neutra e halteres",
  "1276": "Crucifixo unilateral declinado com halter",
  "1617": "Supino unilateral declinado com pegada neutra e halter",
  "0305": "Encolhimento declinado com halteres",
  "0304": "Encolhimento declinado com halteres, versão 2",
  "0306": "Extensão de tríceps declinada com halteres",
  "0307": "Crucifixo declinado com rotação e halteres",
  "1437": "Flexão de dedos com halteres",
  "0308": "Crucifixo reto com halteres",
  "1277": "Crucifixo com halteres na bola suíça",
  "1732": "Avanço à frente com extensão de tríceps e halteres",
  "0310": "Elevação frontal com halteres",
  "0309": "Elevação frontal com halteres, versão 2",
  "0311": "Elevação lateral com halteres e polegares para cima",
  "1760": "Agachamento frontal com halter junto ao peito",
  "0313": "Rosca martelo com halteres",
  "1659": "Rosca martelo com halteres na bola suíça",
  "0312": "Rosca martelo com halteres, versão 2",
  "2402": "Rosca martelo com halteres e suporte para braços",
  "1664": "Rosca alta com halteres",
  "3545": "Supino inclinado alternado com halteres",
  "0314": "Supino inclinado com halteres",
  "0315": "Rosca bíceps no banco inclinado com halteres",
  "0316": "Supino inclinado com halteres",
  "0318": "Rosca inclinada com halteres",
  "0317": "Rosca inclinada com halteres, versão 2",
  "0319": "Crucifixo inclinado com halteres",
  "1278": "Crucifixo inclinado com halteres na bola suíça",
  "0320": "Rosca martelo no banco inclinado com halteres",
  "0321": "Supino inclinado com pegada neutra e halteres",
  "1618": "Supino inclinado com pegada neutra e halteres na bola suíça",
  "0322": "Rosca bíceps interna no banco inclinado com halteres",
  "1279": "Crucifixo unilateral inclinado com halter",
  "1280": "Crucifixo unilateral inclinado na bola suíça com halter",
  "1619": "Supino unilateral inclinado com pegada neutra e halter",
  "1620": "Supino unilateral inclinado com pegada neutra na bola suíça e halter",
  "0323": "Elevação lateral unilateral no banco inclinado com halter",
  "1281": "Supino inclinado unilateral com halter",
  "1282": "Supino inclinado unilateral na bola suíça com halter",
  "0324": "Supino inclinado com pegada neutra e halteres",
  "1283": "Supino inclinado com halteres na bola suíça",
  "0325": "Desenvolvimento inclinado com halteres",
  "0326": "Crucifixo inverso no banco inclinado com halteres",
  "0327": "Remada no banco inclinado com halteres",
  "0328": "Elevação de ombros no banco inclinado com halteres",
  "0329": "Encolhimento no banco inclinado com halteres",
  "3542": "Elevação em T no banco inclinado com halteres",
  "0330": "Extensão de tríceps no banco inclinado com halteres",
  "0331": "Crucifixo inclinado com rotação e halteres",
  "1733": "Extensão bilateral no banco inclinado com halteres",
  "3541": "Elevação em Y no banco inclinado com halteres",
  "0332": "Crucifixo em pé com halteres",
  "0333": "Coice de tríceps com halteres",
  "1734": "Coice de tríceps com halteres na bola suíça",
  "1660": "Rosca bíceps ajoelhada na bola suíça com halteres",
  "0334": "Elevação lateral com halteres",
  "0335": "Elevação lateral seguida de frontal com halteres",
  "0336": "Avanço com halteres",
  "1658": "Avanço com rosca bíceps e halteres",
  "0337": "Tríceps testa cruzado com halter",
  "1729": "Extensão alternada de tríceps deitado com halteres",
  "0338": "Extensão de cotovelos deitado com halteres",
  "0863": "Rotação externa de ombro deitado com halter",
  "0339": "Flexão de joelhos deitado com halter",
  "0340": "Supino reto com pegada neutra e halteres",
  "2470": "Elevação posterior de ombros deitado no chão com halteres",
  "0341": "Elevação posterior unilateral de ombro deitado com halter",
  "0343": "Supino unilateral deitado com halter",
  "0342": "Supino unilateral deitado com halter, versão 2",
  "0344": "Extensão unilateral de tríceps deitado com pegada pronada e halter",
  "0345": "Elevação lateral posterior unilateral deitado com halter",
  "0346": "Extensão unilateral de tríceps deitado com pegada supinada e halter",
  "0347": "Pronação de antebraços deitado com halteres",
  "2705": "Pronação de antebraços deitado no chão com halteres",
  "1284": "Pullover deitado na bola suíça com halter",
  "1328": "Remada para deltoide posterior deitado com halteres",
  "0348": "Elevação lateral posterior deitado com halteres",
  "1735": "Extensão unilateral de tríceps deitado com halter",
  "0349": "Supinação de antebraços deitado com halteres",
  "2706": "Supinação de antebraços deitado no chão com halteres",
  "1661": "Rosca bíceps deitado de costas com halteres",
  "0350": "Rosca supinada deitado com halteres",
  "0351": "Tríceps testa com halteres",
  "1662": "Rosca bíceps aberta deitado com halteres",
  "0352": "Supino com pegada neutra e halteres",
  "1285": "Crucifixo unilateral no banco com halter",
  "0292": "Remada curvada unilateral com halter",
  "1286": "Crucifixo unilateral na bola suíça com halter",
  "0353": "Rosca concentrada unilateral na bola suíça com halter",
  "1287": "Supino declinado unilateral com halter",
  "1288": "Crucifixo unilateral na bola suíça com halter",
  "1736": "Tríceps francês unilateral na bola suíça com halter",
  "1663": "Rosca martelo unilateral no banco Scott com halter",
  "1621": "Supino unilateral com pegada neutra na bola suíça e halter",
  "1289": "Supino inclinado unilateral com halter",
  "0354": "Coice de tríceps unilateral com halter",
  "0355": "Elevação lateral unilateral com halter",
  "0356": "Elevação lateral unilateral com apoio e halter",
  "1290": "Supino unilateral na bola suíça com halter",
  "1665": "Rosca unilateral de bruços com halter",
  "1666": "Rosca martelo unilateral de bruços com halter",
  "1291": "Pullover unilateral na bola suíça com halter",
  "0358": "Extensão unilateral de punho com halter",
  "0359": "Crucifixo inverso unilateral com apoio e halter",
  "1622": "Supino unilateral com pegada inversa e halter",
  "1414": "Rosca Scott inversa unilateral com halter",
  "1667": "Rosca inversa unilateral de bruços no banco inclinado com halter",
  "1668": "Rosca bíceps unilateral sentada na bola suíça com halter",
  "1669": "Rosca martelo unilateral sentada com halter",
  "1415": "Flexão unilateral de punho com pegada neutra sentado e halter",
  "0361": "Desenvolvimento unilateral com halter",
  "0360": "Desenvolvimento unilateral com halter, versão 2",
  "3888": "Arranco unilateral com halter",
  "1670": "Rosca unilateral em pé com halter",
  "1671": "Rosca martelo unilateral em pé com halter",
  "0362": "Extensão unilateral de tríceps no banco com halter",
  "0363": "Remada alta unilateral com halter",
  "0364": "Flexão unilateral de punho com halter",
  "1672": "Rosca Zottman unilateral no banco Scott com halter",
  "1292": "Crucifixo com halteres em apoio unipodal na bola suíça",
  "0365": "Flexão de punhos com pegada neutra apoiada no banco e halteres",
  "0366": "Flexão unilateral de punho com pegada neutra apoiada no banco e halter",
  "1441": "Extensão unilateral de punho apoiada no banco com halter",
  "0367": "Flexão unilateral de punho apoiada no banco com halter",
  "0368": "Extensão de punhos apoiada no banco com halteres",
  "0369": "Flexão de punhos apoiada no banco com halteres",
  "1329": "Remada curvada com rotação das palmas e halteres",
  "1623": "Supino inclinado com pegada neutra e halteres",
  "0370": "Rosca martelo no banco Scott com halteres",
  "0371": "Agachamento pliométrico com halteres",
  "0372": "Rosca Scott com halteres",
  "1673": "Rosca Scott com halter apoiada na bola suíça",
  "1293": "Supino com halteres na bola suíça",
  "0373": "Extensão de tríceps acima da cabeça com pegada pronada e halter",
  "0374": "Rosca de bruços no banco inclinado com halteres",
  "1674": "Rosca martelo de bruços no banco inclinado com halteres",
  "0375": "Pullover com halter",
  "1294": "Pullover com extensão de quadril na bola suíça e halter",
  "1295": "Pullover na bola suíça com halter",
  "1700": "Desenvolvimento com impulso e halteres",
  "0376": "Elevação lateral com halteres",
  "2292": "Elevação para deltoide posterior com halteres",
  "0377": "Remada para deltoide posterior com halteres",
  "0378": "Crucifixo inverso com halteres",
  "0380": "Elevação lateral posterior com halteres",
  "0379": "Elevação lateral posterior com apoio da cabeça e halteres",
  "0381": "Avanço para trás com halteres",
  "0382": "Rosca bíceps com pegada inversa e halteres",
  "1624": "Supino com pegada inversa e halteres",
  "0383": "Crucifixo inverso com halteres",
  "1330": "Remada unilateral com pegada inversa no banco inclinado e halter",
  "1331": "Remada bilateral com pegada inversa no banco inclinado e halteres",
  "2327": "Remada com pegada inversa e halteres (feminino)",
  "0384": "Rosca Scott inversa com halteres",
  "1675": "Rosca inversa de bruços no banco inclinado com halteres",
  "0385": "Extensão de punhos com halteres",
  "1459": "Levantamento terra romeno com halteres",
  "0386": "Crucifixo inverso com rotação e halteres",
  "2397": "Desenvolvimento Scott com halteres",
  "0387": "Elevação frontal alternada sentada com halteres",
  "1676": "Rosca martelo alternada sentada na bola suíça com halteres",
  "0388": "Desenvolvimento alternado sentado com halteres",
  "3546": "Desenvolvimento de ombros alternado sentado com halteres",
  "0389": "Extensão de tríceps sentado no banco com halter",
  "2317": "Elevação lateral sentada com cotovelos flexionados e halteres"
};
