// pt-BR — índices 663–883 da EXDB
export default {
  "1730": "Coice alternado de tríceps sentado com tronco inclinado e halteres",
  "1737": "Extensão de tríceps sentada com tronco inclinado e halteres",
  "1677": "Rosca bíceps sentada com halteres",
  "0390": "Rosca bíceps sentada na bola suíça com halteres",
  "3547": "Rosca bíceps sentada seguida de desenvolvimento de ombros com halteres",
  "1379": "Elevação de panturrilhas sentada com halteres",
  "0391": "Rosca sentada com halteres",
  "0392": "Elevação frontal sentada com halteres",
  "1678": "Rosca martelo sentada com halteres",
  "0393": "Rosca interna de bíceps sentada com halteres",
  "0394": "Coice de tríceps sentado com halteres",
  "0396": "Elevação lateral sentada com halteres",
  "0395": "Elevação lateral sentada com halteres — variação 2",
  "0397": "Flexão neutra de punhos sentada com halteres",
  "1679": "Rosca bíceps unilateral sentada na bola suíça com uma perna elevada e halter",
  "0398": "Coice unilateral de tríceps sentado com halter",
  "0399": "Rotação externa unilateral do antebraço sentada com halter",
  "0400": "Elevação de panturrilha unilateral sentada com halter",
  "1380": "Elevação de panturrilha unilateral sentada com pegada martelo e halter",
  "1381": "Elevação de panturrilha unilateral sentada com a palma para cima e halter",
  "0401": "Flexão de punhos sentada com as palmas para cima e halteres",
  "0402": "Rosca Scott sentada com halter",
  "0403": "Rosca concentrada inversa sentada com halter",
  "1738": "Extensão unilateral de tríceps acima da cabeça sentada com pegada invertida e halter",
  "0405": "Desenvolvimento de ombros sentado com halteres",
  "0404": "Desenvolvimento de ombros sentado com pegada neutra e halteres",
  "2188": "Extensão de tríceps sentada com halter",
  "0406": "Encolhimento de ombros com halteres",
  "0407": "Flexão lateral do tronco com halter",
  "0408": "Elevação lateral unilateral deitada de lado com halter",
  "3664": "Prancha lateral com crucifixo inverso e halter",
  "3548": "Caminhada unilateral com halter acima da cabeça",
  "0409": "Elevação de panturrilha unilateral com halter",
  "1757": "Levantamento terra unilateral com halteres",
  "2805": "Levantamento terra unilateral com apoio em plataforma e halteres",
  "0410": "Agachamento búlgaro unilateral com halteres",
  "0411": "Agachamento unilateral com halteres",
  "0413": "Agachamento com halteres",
  "3560": "Rosca martelo alternada seguida de desenvolvimento em pé com halteres",
  "0414": "Desenvolvimento alternado acima da cabeça em pé com halteres",
  "0415": "Elevação lateral alternada em pé com halteres",
  "1739": "Coice alternado de tríceps em pé com halteres",
  "2143": "Elevação ao redor do mundo em pé com halteres",
  "1740": "Extensão unilateral de tríceps em pé com tronco inclinado e halter",
  "1741": "Extensão de tríceps em pé com tronco inclinado e halteres",
  "0416": "Rosca bíceps em pé com halteres",
  "0417": "Elevação de panturrilhas em pé com halteres",
  "0418": "Rosca concentrada em pé com halteres",
  "0419": "Elevação frontal acima da cabeça em pé com halteres",
  "2321": "Rosca interna de bíceps em pé com halteres — variação 2",
  "0420": "Coice de tríceps em pé com halteres",
  "0421": "Rosca concentrada unilateral em pé com halter",
  "0422": "Rosca unilateral em pé apoiada no banco inclinado com halter",
  "1680": "Rosca unilateral em pé apoiada no banco inclinado com halter",
  "0423": "Extensão unilateral de tríceps em pé com halter",
  "0424": "Desenvolvimento unilateral em pé com pegada neutra e halter",
  "0425": "Rosca inversa unilateral em pé com halter",
  "0426": "Desenvolvimento acima da cabeça em pé com halteres",
  "0427": "Desenvolvimento em pé com pegada neutra e halteres",
  "0428": "Rosca Scott em pé com halteres",
  "0429": "Rosca inversa em pé com halteres",
  "0430": "Extensão de tríceps em pé com halter",
  "2293": "Rosca Scott Zottman em pé com halteres",
  "1684": "Subida na plataforma com equilíbrio unilateral e rosca bíceps com halteres",
  "0431": "Subida na plataforma com halteres",
  "2796": "Subida na plataforma com afundo e halteres",
  "2812": "Subida na plataforma com agachamento dividido e halteres",
  "0432": "Levantamento terra com pernas semirrígidas e halteres",
  "0433": "Pullover com braços estendidos e halter",
  "0434": "Levantamento terra com pernas estendidas e halteres",
  "2808": "Agachamento sumô com puxada do halter entre as pernas",
  "2803": "Agachamento com apoio e halteres",
  "0436": "Extensão Tate de tríceps com halteres",
  "1742": "Coice de tríceps em apoio unipodal com halteres",
  "1743": "Supino com rotação e halteres",
  "0437": "Remada alta com halteres",
  "1765": "Remada alta com halteres (vista posterior)",
  "0864": "Rotação externa de ombros em pé com halteres",
  "5201": "Rosca garçom com halteres",
  "0438": "Desenvolvimento em W com halteres",
  "0439": "Rosca Zottman com halteres",
  "2294": "Rosca Scott Zottman com halteres",
  "2189": "Extensão de tríceps sentada com halteres",
  "1167": "Alongamento dinâmico de peitoral (masculino)",
  "3287": "Mergulho nos cotovelos",
  "1772": "Elevação pelos cotovelos — flexão inversa",
  "0443": "Abdominal cotovelo ao joelho",
  "3292": "Inclinação e elevação do tronco",
  "1332": "Elevação alternada dos braços na bola suíça",
  "1333": "Extensão lombar na bola suíça com braços estendidos",
  "1334": "Extensão lombar na bola suíça com as mãos atrás da cabeça",
  "1335": "Extensão lombar na bola suíça com os joelhos fora do chão",
  "1336": "Extensão lombar com rotação na bola suíça",
  "1744": "Mergulho de tríceps na bola suíça",
  "1559": "Alongamento dos flexores do quadril na bola suíça",
  "1338": "Alongamento abraçando a bola suíça",
  "1339": "Alongamento de dorsais na bola suíça",
  "1341": "Alongamento lombar em pirâmide na bola suíça",
  "1342": "Alongamento lateral de dorsais deitado na bola suíça",
  "1382": "Elevação de panturrilhas na parede com bola suíça",
  "3241": "Elevação de panturrilhas na parede com bola suíça e bola de tênis entre os tornozelos",
  "3240": "Elevação de panturrilhas na parede com bola suíça e bola de tênis entre os joelhos",
  "1416": "Rotação externa unilateral da perna em pronação na bola suíça",
  "1417": "Flexão de joelho com chute diagonal unilateral na bola suíça",
  "1296": "Flexão em V invertido na bola suíça",
  "1343": "Elevação de pernas em pronação na bola suíça",
  "1560": "Alongamento de posteriores de coxa sentado na bola suíça",
  "1745": "Alongamento de tríceps sentado na bola suíça",
  "1746": "Extensão de tríceps deitada de costas na bola suíça",
  "1747": "Tríceps francês com barra EZ na bola suíça",
  "3010": "Pullover deitado com braços flexionados e barra EZ",
  "1748": "Extensão de tríceps deitada com pegada fechada atrás da cabeça e barra EZ",
  "1344": "Remada curvada com pegada supinada e barra EZ",
  "1682": "Rosca concentrada sentada com pegada fechada e barra EZ",
  "1749": "Tríceps francês em pé com barra EZ",
  "0445": "Desenvolvimento acima da cabeça com barra EZ",
  "1627": "Rosca Scott com pegada fechada e barra EZ",
  "0446": "Rosca bíceps com pegada fechada e barra EZ",
  "0447": "Rosca bíceps com barra EZ",
  "0448": "Tríceps testa declinado com pegada fechada e barra EZ",
  "2186": "Extensão de tríceps em banco declinado com barra EZ",
  "0449": "Extensão de tríceps em banco inclinado com barra EZ",
  "0450": "Supino JM com barra EZ",
  "0451": "Rosca inversa com barra EZ",
  "0452": "Rosca Scott inversa com barra EZ",
  "1458": "Rosca bíceps sentada com barra EZ",
  "0453": "Extensão de tríceps sentada com barra EZ",
  "0454": "Rosca aranha com barra EZ",
  "1628": "Rosca aranha com barra EZ",
  "2404": "Rosca bíceps com barra EZ e isolador de braços",
  "2432": "Supino fechado com barra EZ",
  "2741": "Rosca bíceps em pé com pegada aberta e barra EZ",
  "2133": "Caminhada do fazendeiro",
  "0455": "Flexão de dedos",
  "3303": "Bandeira humana",
  "0456": "Abdominal com os joelhos flexionados",
  "0457": "Abdominal canivete com braços estendidos",
  "0458": "Crucifixo no chão com barra",
  "0459": "Batimento alternado de pernas",
  "1472": "Salto para a frente",
  "3470": "Avanço à frente (masculino)",
  "3194": "Agachamento Frankenstein",
  "2429": "Abdominal sapinho",
  "3301": "Prancha sapo",
  "3296": "Alavanca frontal",
  "3295": "Repetições de alavanca frontal",
  "0464": "Prancha frontal com rotação",
  "3315": "Maltês completo",
  "3299": "Prancha completa",
  "3327": "Flexão em prancha completa",
  "0466": "Barra fixa Gironda ao esterno",
  "3561": "Ponte de glúteos com marcha alternada",
  "3523": "Ponte de glúteos com as duas pernas no banco (masculino)",
  "3193": "Flexão de joelhos na máquina de glúteos e posteriores",
  "0467": "Barra fixa gorila",
  "0469": "Abdominal com joelhos ao peito",
  "1383": "Elevação de panturrilhas na máquina hack",
  "1384": "Elevação unilateral de panturrilha na máquina hack",
  "3221": "Semiflexão de joelhos (masculino)",
  "3202": "Meio abdominal (masculino)",
  "1511": "Alongamento de posteriores de coxa",
  "2139": "Bicicleta ergométrica de braços",
  "3218": "Toque circular dos pés com as mãos entrelaçadas (masculino)",
  "3215": "Toque circular dos pés com as mãos entrelaçadas atrás do corpo (masculino)",
  "3302": "Parada de mãos",
  "0471": "Flexão na parada de mãos",
  "1764": "Elevação de quadril com as pernas suspensas",
  "0472": "Elevação de pernas suspensa",
  "1761": "Elevação oblíqua dos joelhos suspensa",
  "0473": "Canivete suspenso",
  "0474": "Elevação de quadril com as pernas estendidas suspensa",
  "0475": "Elevação de pernas estendidas suspensa",
  "0476": "Elevação de quadril com as pernas estendidas e rotação, suspensa",
  "3636": "Elevação dos joelhos contra a parede",
  "0484": "Elevação de quadril com os joelhos flexionados",
  "1418": "Abraço dos joelhos ao peito",
  "3234": "Crucifixo Hyght com halteres",
  "0489": "Hiperextensão",
  "0488": "Hiperextensão no banco",
  "3289": "Mergulho impossível",
  "1471": "Caminhada da lagarta",
  "3698": "Caminhada da lagarta — variação 2",
  "0490": "Flexão inclinada com pegada fechada",
  "0491": "Elevação de quadril com as pernas estendidas em banco inclinado",
  "0492": "Flexão inclinada com salto em profundidade",
  "0493": "Flexão inclinada",
  "3785": "Flexão inclinada sobre caixa",
  "0494": "Flexão inclinada com pegada invertida",
  "3011": "Flexão escapular inclinada",
  "0495": "Abdominal inclinado com rotação",
  "1564": "Alongamento intermediário dos flexores do quadril e quadríceps",
  "0496": "Flexão inversa de joelhos com apoio no banco",
  "2400": "Flexão inversa de joelhos na máquina de puxada alta",
  "0499": "Remada invertida",
  "2300": "Remada invertida com os joelhos flexionados",
  "2298": "Remada invertida no banco",
  "0497": "Remada invertida — variação 2",
  "0498": "Remada invertida com fitas de suspensão",
  "1419": "Alongamento cruz de ferro",
  "1297": "Compressão isométrica de peitoral",
  "0500": "Limpador de para-brisa isométrico",
  "0501": "Burpee com polichinelo",
  "3224": "Polichinelo com salto (masculino)",
  "0507": "Abdominal canivete",
  "0508": "Abdominal Janda",
  "2612": "Pular corda",
  "0514": "Agachamento com salto",
  "0513": "Agachamento com salto — variação 2",
  "0517": "Moinho avançado com kettlebell",
  "0518": "Levantamento alternado ao ombro a partir da suspensão com kettlebells",
  "0520": "Desenvolvimento alternado com kettlebell",
  "0519": "Desenvolvimento alternado no chão com kettlebell",
  "0521": "Remada renegada alternada com kettlebell",
  "0522": "Remada alternada com kettlebell",
  "0523": "Desenvolvimento Arnold com kettlebell",
  "0524": "Desenvolvimento inclinado lateral com kettlebell",
  "0525": "Levantamento invertido ao ombro a partir da suspensão com kettlebell",
  "0526": "Levantamento alternado duplo ao ombro a partir da suspensão com kettlebells",
  "0527": "Arremesso duplo com kettlebells",
  "0528": "Desenvolvimento duplo com impulso e kettlebells",
  "0529": "Arranco duplo com kettlebells"
};
